name: CI

on:
  workflow_dispatch:
  pull_request:
    paths:
      - gcl
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: haskell-actions/run-ormolu@v17

  build:
    needs: check
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - macos-latest
          - ubuntu-latest

    # this is dumb https://stackoverflow.com/q/58139175
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
        working-directory: ./gcl
      - uses: haskell-actions/setup@v2
        with:
          enable-stack: true
        working-directory: ./gcl

      - name:
        run: stack build
        working-directory: ./gcl

      # TODO: `stack test` is broken currently
      # reenable this in the future
      # - name:
      #   run: stack test
      #   working-directory: ./gcl
